import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Exemplo de Navigation Bar responsivo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Exemplo de Navigation Bar responsivo.
          </h1>

          <p className={styles.description}>
            Para ver o resultado, redimensione a janela do navegador até ela
            chegar no tamanho comum a dispositivos móveis.
          </p>
        </main>
      </div>
    </>
  );
}
